#!/bin/bash

set -e

# plan, apply, destroy, test

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -a|--action)
      ACTION="$2"
      shift # past argument
      shift # past value
      ;;
    -v|--version)
      VERSION="$2"
      shift # past argument
      shift # past value
      ;;
    -e|--environment)
      ENVIRONMENT="$2"
      shift # past argument
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

echo "Terraform Action: $ACTION"
echo "Terraform Version: $VERSION"
echo "Environment: $ENVIRONMENT"
echo $POSITIONAL_ARGS

#terraform init

#terraform validate
